- name: '[docker role] Adding docker gpg'
  apt_key:
    url: '{{ docker_url_gpg }}'
    state: present

- name: '[docker role] Adding docker repository'
  apt_repository:
    repo: 'deb [arch=amd64] {{ docker_url_repo }} buster stable'
    state: present
    filename: docker-ce

- name: '[docker role] Installing docker-ce'
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
    state: present
    update_cache: yes
  notify:
    - Creating systemd docker.service.d directory /etc/systemd/system/docker.service.d
    - Setting Docker's cgroupdriver to systemd
    - Restarting docker.io
