version: '3'
services:
  rabbitmq0:
    environment:
      - "RABBITMQ_DEFAULT_USER={{ rabbitmq_cluster_default_user }}"
      - "RABBITMQ_DEFAULT_PASS={{ rabbitmq_cluster_default_pass }}"
      - "RABBITMQ_ERLANG_COOKIE={{ rabbitmq_cluster_erlang_cookie }}"
    image: rabbitmq:3.8.16-management 
    hostname: rabbitmq0
    container_name: rabbitmq0
    restart: always
    networks:
      - rabbitmq
    ports:
      - 8080:15672
    volumes:
      - rabbitmq0_data:/var/lib/rabbitmq
  rabbitmq1:
    environment:
      - "RABBITMQ_DEFAULT_USER={{ rabbitmq_cluster_default_user }}"
      - "RABBITMQ_DEFAULT_PASS={{ rabbitmq_cluster_default_pass }}"
      - "RABBITMQ_ERLANG_COOKIE={{ rabbitmq_cluster_erlang_cookie }}"
    image: rabbitmq:3.8.16-management 
    hostname: rabbitmq1
    container_name: rabbitmq1
    restart: always
    networks:
      - rabbitmq
    ports:
      - 8081:15672
    volumes:
      - rabbitmq1_data:/var/lib/rabbitmq
  rabbitmq2:
    environment:
      - "RABBITMQ_DEFAULT_USER={{ rabbitmq_cluster_default_user }}"
      - "RABBITMQ_DEFAULT_PASS={{ rabbitmq_cluster_default_pass }}"
      - "RABBITMQ_ERLANG_COOKIE={{ rabbitmq_cluster_erlang_cookie }}"
    image: rabbitmq:3.8.16-management 
    hostname: rabbitmq2
    container_name: rabbitmq2
    restart: always
    networks:
      - rabbitmq
    ports:
      - 8082:15672
    volumes:
      - rabbitmq2_data:/var/lib/rabbitmq
networks:
  rabbitmq:
volumes:
  rabbitmq0_data:
  rabbitmq1_data:
  rabbitmq2_data:

